CREATE TABLE ESTUDIANTE 
(id_estudiante INTEGER NOT NULL PRIMARY KEY, 
nombre_est VARCHAR (20) NOT NULL,
apellido VARCHAR (20) NOT NULL);

CREATE TABLE CURSO (id_curso INTEGER NOT NULL PRIMARY KEY,
nombre_curso VARCHAR (20) NOT NULL,
nro_creditos INTEGER NOT NULL);

CREATE TABLE PROFESOR (id_profesor INTEGER NOT NULL PRIMARY KEY,
nombre_prof VARCHAR (15) NOT NULL,
apellido_prof VARCHAR (15) NOT NULL);

CREATE TABLE GRUPO (idcurso INTEGER REFERENCES CURSO,
idgrupo VARCHAR (5) NOT NULL,
cupo INTEGER NOT NULL,
PRIMARY KEY (idcurso, idgrupo));

CREATE TABLE MATRICULA (idest INTEGER REFERENCES ESTUDIANTE, 
idcur INTEGER,
idgrupo VARCHAR (5),
PRIMARY KEY (idest, idcur, idgrupo),
FOREIGN KEY (idcur, idgrupo) REFERENCES GRUPO);


CREATE TABLE DICTA (idprof INTEGER REFERENCES PROFESOR,
idcurso INTEGER ,
idgrupo VARCHAR (5) ,
fechainicio DATE NULL,
fechafin DATE NULL,
PRIMARY KEY (idprof,idcurso, idgrupo),
FOREIGN KEY (idcurso, idgrupo) REFERENCES GRUPO);
