
CREATE TABLE CARRITO
(Codigo_carr INTEGER NOT NULL,
Cantidad INTEGER NOT NULL,
Subtotal NUMERIC NOT NULL,
Total NUMERIC NOT NULL,
PRIMARY KEY (Codigo_carr));


CREATE TABLE CIUDAD
(Cod_ciudad INTEGER NOT NULL,
Nom_Ciudad VARCHAR(20) NOT NULL,
Departamento VARCHAR(20) NOT NULL,
PRIMARY KEY (Cod_ciudad));

CREATE TABLE USUARIO 
(Cedula INTEGER NOT NULL,
Nombre VARCHAR(20) NOT NULL,
Apellido VARCHAR(20) NOT NULL,
Direccion VARCHAR (50) NOT NULL, 
Cod_ciu INTEGER NOT NULL,
FOREIGN KEY (Cod_ciu) REFERENCES CIUDAD,
PRIMARY KEY (Cedula));

CREATE TABLE VENDEDOR 
(U_cc INTEGER NOT NULL,
Calificacion INTEGER NULL,
VentasExitosas INTEGER NULL,
PRIMARY KEY (U_cc),
FOREIGN KEY (U_cc) REFERENCES USUARIO);


CREATE TABLE COMPRADOR
(codcompr INTEGER NOT NULL,
U_cc INTEGER NOT NULL,
Cod_carro INTEGER NOT NULL,
PRIMARY KEY (codcompr),
FOREIGN KEY (U_cc) REFERENCES USUARIO,
FOREIGN KEY (Cod_carro) REFERENCES CARRITO);


CREATE TABLE PRODUCTO
(Codigo_prod INTEGER NOT NULL,
Categoria VARCHAR (15) NOT NULL,
Marca VARCHAR(20) NOT NULL,
Referencia VARCHAR (20) NOT NULL,
Precio NUMERIC NOT NULL,
Cantidad INTEGER NOT NULL,
Estado VARCHAR(10) NOT NULL,
Calificacion INTEGER NULL,
Cod_carr INTEGER NOT NULL,
PRIMARY KEY (Codigo_prod),
FOREIGN KEY (Cod_carr) REFERENCES CARRITO);

CREATE TABLE COMPRA(
Cod_Compra INTEGER NOT NULL,
Fecha_compra DATE NULL,
Cod_carr INTEGER NOT NULL, 
cod_comprador INTEGER NOT NULL,
PRIMARY KEY (Cod_Compra),
FOREIGN KEY (Cod_carr) REFERENCES CARRITO,
FOREIGN KEY (cod_comprador) REFERENCES COMPRADOR);

CREATE TABLE ENVIO
(Cod_seguimiento INTEGER NOT NULL,
FechaEnvio DATE NULL,
DireccionSalida VARCHAR (50) NOT NULL,
DireccionLlegada VARCHAR (50) NOT NULL,
Cod_carr INTEGER NOT NULL,
PRIMARY KEY (Cod_seguimiento),
FOREIGN KEY (Cod_carr) REFERENCES CARRITO);

CREATE TABLE TIPOPAGO
(Cod_carr INTEGER NOT NULL,
PRIMARY KEY (Cod_carr), 
FOREIGN KEY (Cod_carr) REFERENCES CARRITO);

CREATE TABLE TARJETA
(Num_tarjeta INTEGER NOT NULL,
Cupo INTEGER NOT NULL,
Cod_carr INTEGER NOT NULL,
PRIMARY KEY (Num_tarjeta),
FOREIGN KEY (Cod_carr) REFERENCES TIPOPAGO);

CREATE TABLE PAYPAL
(Cuenta_ppal VARCHAR(20) NOT NULL,
Saldo NUMERIC NOT NULL,
Cod_carr INTEGER NOT NULL,
PRIMARY KEY (Cuenta_ppal),
FOREIGN KEY (Cod_carr) REFERENCES TIPOPAGO);

CREATE TABLE COMENTARIO 
(Cod_coment INTEGER NOT NULL,
Fecha_pub DATE NULL,
Publicador INTEGER NOT NULL,
Cod_vendedor INTEGER NULL,
Cod_producto INTEGER NULL,
Comentario VARCHAR (50) NULL,
PRIMARY KEY (Cod_coment),
FOREIGN KEY (Publicador) REFERENCES COMPRADOR,
FOREIGN KEY (Cod_vendedor) REFERENCES VENDEDOR,
FOREIGN KEY (Cod_producto) REFERENCES PRODUCTO);

ALTER TABLE PRODUCTO DROP COLUMN Cantidad;