-- Restricciones de integridad
-- MANTENIMIENTO

-- PRIMARY KEYS

ALTER TABLE DEPARTAMENTOS ADD CONSTRAINT DEP_PK PRIMARY KEY(COD);
ALTER TABLE EQUIPOS ADD CONSTRAINT EQU_PK PRIMARY KEY(COD);
ALTER TABLE PARTES ADD CONSTRAINT PAR_PK PRIMARY KEY(COD);
ALTER TABLE VCONTROL ADD CONSTRAINT VCO_PK PRIMARY KEY(COD);
ALTER TABLE EMPLEADOS ADD CONSTRAINT EMP_PK PRIMARY KEY(COD);
ALTER TABLE JMANTENIMIENTOS ADD CONSTRAINT JMA_PK PRIMARY KEY(COD);
ALTER TABLE JDEPARTAMENTOS ADD CONSTRAINT JDE_PK PRIMARY KEY(COD);
ALTER TABLE EBODEGAS ADD CONSTRAINT EBO_PK PRIMARY KEY(COD);
ALTER TABLE ACCORRECTIVAS ADD CONSTRAINT ACC_PK PRIMARY KEY(COD);
ALTER TABLE PERIODICIDADES ADD CONSTRAINT PER_PK PRIMARY KEY(COD);
ALTER TABLE MPREVENTIVOS ADD CONSTRAINT MPR_PK PRIMARY KEY(ID);
ALTER TABLE MCORRECTIVOS ADD CONSTRAINT MCO_PK PRIMARY KEY(ID);
ALTER TABLE OTRABAJOS ADD CONSTRAINT OTR_PK PRIMARY KEY(COD);
ALTER TABLE VAR_PAR ADD CONSTRAINT VPR_PK PRIMARY KEY(COD_OTR, COD_VCO, COD_PAR, COD_EMP);
ALTER TABLE PRODUCTOS ADD CONSTRAINT PRO_PK PRIMARY KEY(COD);
ALTER TABLE BODEGAS ADD CONSTRAINT BOD_PK PRIMARY KEY(COD);
ALTER TABLE SOLICITUDES ADD CONSTRAINT SOL_PK PRIMARY KEY(COD, COD_OTR, COD_PRO, COD_JMA);
ALTER TABLE BOD_PRO ADD CONSTRAINT BDP_PK PRIMARY KEY(COD_BOD, COD_PRO);
ALTER TABLE NOTIFICACIONES ADD CONSTRAINT NOT_PK PRIMARY KEY(COD);
ALTER TABLE PROVEEDORES ADD CONSTRAINT PRV_PK PRIMARY KEY(ID);
ALTER TABLE COMPRAS ADD CONSTRAINT COM_PK PRIMARY KEY(COD);
ALTER TABLE COM_PRO ADD CONSTRAINT CPR_PK PRIMARY KEY(COD_PRO, COD_COM);

-- FOREIGN KEYS

ALTER TABLE EQUIPOS ADD CONSTRAINT EQU_DEP_FK FOREIGN KEY(COD_DEP) REFERENCES DEPARTAMENTOS(COD);
ALTER TABLE PARTES ADD CONSTRAINT PAR_EQU_FK FOREIGN KEY(COD_EQU) REFERENCES EQUIPOS(COD);
ALTER TABLE EMPLEADOS ADD CONSTRAINT EMP_DEP_FK FOREIGN KEY(COD_DEP) REFERENCES DEPARTAMENTOS(COD);
ALTER TABLE ACCORRECTIVAS ADD CONSTRAINT ACC_JMA_FK FOREIGN KEY(COD_JMA) REFERENCES JMANTENIMIENTOS(COD);
ALTER TABLE MPREVENTIVOS ADD CONSTRAINT MPR_PER_FK FOREIGN KEY(COD_PER) REFERENCES PERIODICIDADES(COD);
ALTER TABLE MCORRECTIVOS ADD CONSTRAINT MCO_EQU_FK FOREIGN KEY(COD_EQU) REFERENCES EQUIPOS(COD);
ALTER TABLE MCORRECTIVOS ADD CONSTRAINT MCO_ACC_FK FOREIGN KEY(COD_ACC) REFERENCES ACCORRECTIVAS(COD);
ALTER TABLE OTRABAJOS ADD CONSTRAINT OTR_MPR_FK FOREIGN KEY(ID_MPR) REFERENCES MPREVENTIVOS(ID);
ALTER TABLE OTRABAJOS ADD CONSTRAINT OTR_MCO_FK FOREIGN KEY(ID_MCO) REFERENCES MCORRECTIVOS(ID);
ALTER TABLE VAR_PAR ADD CONSTRAINT VPR_OTR_FK FOREIGN KEY(COD_OTR) REFERENCES OTRABAJOS(COD);
ALTER TABLE VAR_PAR ADD CONSTRAINT VPR_VCO_FK FOREIGN KEY(COD_VCO) REFERENCES VCONTROL(COD);
ALTER TABLE VAR_PAR ADD CONSTRAINT VPR_PAR_FK FOREIGN KEY(COD_PAR) REFERENCES PARTES(COD);
ALTER TABLE VAR_PAR ADD CONSTRAINT VPR_EMP_FK FOREIGN KEY(COD_EMP) REFERENCES EMPLEADOS(COD);
ALTER TABLE SOLICITUDES ADD CONSTRAINT SOL_OTR_FK FOREIGN KEY(COD_OTR) REFERENCES OTRABAJOS(COD);
ALTER TABLE SOLICITUDES ADD CONSTRAINT SOL_JMA_FK FOREIGN KEY(COD_JMA) REFERENCES JMANTENIMIENTOS(COD);
ALTER TABLE SOLICITUDES ADD CONSTRAINT SOL_PRO_FK FOREIGN KEY(COD_PRO) REFERENCES PRODUCTOS(COD);
ALTER TABLE BOD_PRO ADD CONSTRAINT BDP_BOD_FK FOREIGN KEY(COD_BOD) REFERENCES BODEGAS(COD);
ALTER TABLE BOD_PRO ADD CONSTRAINT BDP_PRO_FK FOREIGN KEY(COD_PRO) REFERENCES PRODUCTOS(COD);
ALTER TABLE NOTIFICACIONES ADD CONSTRAINT NOT_PRO_FK FOREIGN KEY(COD_PRO) REFERENCES PRODUCTOS(COD);
ALTER TABLE NOTIFICACIONES ADD CONSTRAINT NOT_EMP_FK FOREIGN KEY(COD_EMP) REFERENCES EMPLEADOS(COD);
ALTER TABLE NOTIFICACIONES ADD CONSTRAINT NOT_JMA_FK FOREIGN KEY(COD_JMA) REFERENCES JMANTENIMIENTOS(COD);
ALTER TABLE NOTIFICACIONES ADD CONSTRAINT NOT_JDE_FK FOREIGN KEY(COD_JDE) REFERENCES JDEPARTAMENTOS(COD);
ALTER TABLE NOTIFICACIONES ADD CONSTRAINT NOT_EBO_FK FOREIGN KEY(COD_EBO) REFERENCES EBODEGAS(COD);
ALTER TABLE NOTIFICACIONES ADD CONSTRAINT NOT_OTR_FK FOREIGN KEY(COD_OTR) REFERENCES OTRABAJOS(COD);
ALTER TABLE COMPRAS ADD CONSTRAINT COM_EBO_FK FOREIGN KEY(COD_EBO) REFERENCES EBODEGAS(COD);
ALTER TABLE COMPRAS ADD CONSTRAINT COM_PRV_FK FOREIGN KEY(ID_PRV) REFERENCES PROVEEDORES(ID);
ALTER TABLE COM_PRO ADD CONSTRAINT CPR_COM_FK FOREIGN KEY(COD_COM) REFERENCES COMPRAS(COD);
ALTER TABLE COM_PRO ADD CONSTRAINT CPR_PRO_FK FOREIGN KEY(COD_PRO) REFERENCES PRODUCTOS(COD);

-- UNIQUE KEYS

--NO HAY...

-- CHECK KEYS

ALTER TABLE BOD_PRO ADD CONSTRAINT BDP_CAN_CK CHECK (CANTIDAD >= 0 );
ALTER TABLE SOLICITUDES ADD CONSTRAINT SOL_CAN_CK CHECK (CANTIDAD >= 0 );
ALTER TABLE COM_PRO ADD CONSTRAINT CPR_CAN_CK CHECK (CANTIDAD >= 0 );
ALTER TABLE NOTIFICACIONES ADD CONSTRAINT NOT_CAN_CK CHECK (CANTIDAD >= 0 );
