-- Script de eliminación de tablas (uninstall)
-- MANTENIMIENTO

DROP TABLE COM_PRO CASCADE;
DROP TABLE COMPRAS CASCADE;
DROP TABLE PROVEEDORES CASCADE;
DROP TABLE NOTIFICACIONES CASCADE;
DROP TABLE BOD_PRO CASCADE;
DROP TABLE SOLICITUDES CASCADE;
DROP TABLE BODEGAS CASCADE;
DROP TABLE PRODUCTOS CASCADE;
DROP TABLE VAR_PAR CASCADE;
DROP TABLE OTRABAJOS CASCADE;
DROP TABLE MCORRECTIVOS CASCADE;
DROP TABLE MPREVENTIVOS CASCADE;
DROP TABLE PERIODICIDADES CASCADE;
DROP TABLE ACCORRECTIVAS CASCADE;
DROP TABLE EBODEGAS CASCADE;
DROP TABLE JDEPARTAMENTOS CASCADE;
DROP TABLE JMANTENIMIENTOS CASCADE;
DROP TABLE EMPLEADOS CASCADE;
DROP TABLE VCONTROL CASCADE;
DROP TABLE PARTES CASCADE;
DROP TABLE EQUIPOS CASCADE;
DROP TABLE DEPARTAMENTOS CASCADE;
