/* Creación de tablas */


-- Script para creación de tablas (install)
-- MANTENIMIENTO

CREATE TABLE DEPARTAMENTOS(
	 COD SERIAL NOT NULL, 
	 NOMBRE VARCHAR(20) NOT NULL, 
	 ACTIVIDAD VARCHAR(20));

CREATE TABLE EQUIPOS(
	 COD SERIAL NOT NULL, 
	 TIPO VARCHAR(20) NOT NULL, 
	 ESTADO VARCHAR(20),
	 COD_DEP INT NOT NULL);

CREATE TABLE PARTES(
	 COD SERIAL NOT NULL, 
	 NOMBRE VARCHAR(20) NOT NULL, 
	 ESTADO VARCHAR(20),
	 COD_EQU INT NOT NULL);

CREATE TABLE VCONTROL(
	 COD SERIAL NOT NULL, 
	 TIPO VARCHAR(20) NOT NULL);

CREATE TABLE EMPLEADOS(
	 COD SERIAL NOT NULL, 
	 NOMBRE VARCHAR(20) NOT NULL, 
	 ESTADO VARCHAR(20) NOT NULL,
	 JORNADA VARCHAR(20) NOT NULL,
	 COD_DEP INT NOT NULL);

CREATE TABLE JMANTENIMIENTOS(
	 COD SERIAL NOT NULL, 
	 NOMBRE VARCHAR(20) NOT NULL, 
	 ESTADO VARCHAR(20) NOT NULL,
	 JORNADA VARCHAR(20) NOT NULL,
	 COD_DEP INT NOT NULL);

CREATE TABLE JDEPARTAMENTOS(
	 COD SERIAL NOT NULL, 
	 NOMBRE VARCHAR(20) NOT NULL, 
	 ESTADO VARCHAR(20) NOT NULL,
	 JORNADA VARCHAR(20) NOT NULL,
	 COD_DEP INT NOT NULL);

CREATE TABLE EBODEGAS(
	 COD SERIAL NOT NULL, 
	 NOMBRE VARCHAR(20) NOT NULL, 
	 ESTADO VARCHAR(20) NOT NULL,
	 JORNADA VARCHAR(20) NOT NULL);

CREATE TABLE ACCORRECTIVAS(
	 COD SERIAL NOT NULL, 
	 TIEMPO TIME NOT NULL,
	 COD_JMA INT NOT NULL);

CREATE TABLE PERIODICIDADES(
	 COD SERIAL NOT NULL,
	 TIEMPO TIME NOT NULL);

CREATE TABLE MPREVENTIVOS(
	 ID SERIAL NOT NULL, 
	 ESTADO VARCHAR(20) NOT NULL,
	 TIPO VARCHAR(20) NOT NULL,
	 COD_EQU INT NOT NULL,
	 COD_PER INT NOT NULL);

CREATE TABLE MCORRECTIVOS(
	 ID SERIAL NOT NULL, 
	 ESTADO VARCHAR(20) NOT NULL,
	 TIPO VARCHAR(20) NOT NULL,
	 COD_EQU INT NOT NULL,
	 COD_ACC INT NOT NULL);

CREATE TABLE OTRABAJOS(
	 COD SERIAL NOT NULL, 
	 HORA TIME NOT NULL, 
	 ESTADO VARCHAR(20),
	 ID_MPR INT,
	 ID_MCO INT);

CREATE TABLE VAR_PAR(
	 MEDIDA VARCHAR(20) NOT NULL,
	 COD_OTR INT NOT NULL, 
	 COD_VCO INT NOT NULL,
	 COD_PAR INT NOT NULL,
	 COD_EMP INT NOT NULL);

CREATE TABLE PRODUCTOS(
	 COD SERIAL NOT NULL, 
	 NOMBRE VARCHAR(20) NOT NULL);

CREATE TABLE BODEGAS(
	 COD SERIAL NOT NULL);

CREATE TABLE SOLICITUDES(
	 COD SERIAL NOT NULL, 
	 ESTADO VARCHAR(20) DEFAULT 'INCOMPLETA',
	 CANTIDAD INT NOT NULL,
	 COD_OTR INT NOT NULL,
	 COD_JMA INT NOT NULL,
	 COD_PRO INT NOT NULL);

CREATE TABLE BOD_PRO(
	 COD_BOD INT NOT NULL, 
	 COD_PRO INT NOT NULL,
	 CANTIDAD INT NOT NULL);

CREATE TABLE NOTIFICACIONES(
	 COD SERIAL NOT NULL, 
	 DESCRIPCION VARCHAR(100) NOT NULL,
	 CANTIDAD INT,
	 COD_SOL INT,
	 COD_PRO INT,
	 COD_EMP INT,
	 COD_JMA INT,
	 COD_JDE INT,
	 COD_EBO INT,
	 COD_OTR INT);

CREATE TABLE PROVEEDORES(
	 ID SERIAL NOT NULL, 
	 NOMBRE VARCHAR(20) NOT NULL);

CREATE TABLE COMPRAS(
	 COD SERIAL NOT NULL, 
	 FECHA DATE NOT NULL,
	 COD_EBO INT NOT NULL,
	 ID_PRV INT NOT NULL);

CREATE TABLE COM_PRO(
	 COD_COM INT NOT NULL, 
	 COD_PRO INT NOT NULL,
	 CANTIDAD INT NOT NULL);
