
 --Proyecto hecho por Andrés Guerrero, Jairo Quintero


CREATE TABLE LIBROS 
(ISBN INTEGER NOT NULL,
TITULO VARCHAR(20) NOT NULL,
EDITORIAL VARCHAR (20) NOT NULL,
AUTOR VARCHAR (25) NOT NULL,
EDICION INTEGER NULL,
AÑO INTEGER NOT NULL,
MATERIA VARCHAR(20) NULL,
RESUMEN VARCHAR (200) NOT NULL,
PRIMARY KEY (ISBN)
);

CREATE TABLE COLECCIONLIBRO
(ISBN INTEGER NOT NULL,
NUMSOLICITACION INTEGER NOT NULL CHECK  (NUMSOLICITACION > 3),
FOREIGN KEY (ISBN) REFERENCES LIBROS
);


CREATE TABLE UBICACIONLIBRO
(ISBN INTEGER NOT NULL,
PISO INTEGER NOT NULL,
ESTANTE INTEGER NOT NULL,
FOREIGN KEY (ISBN) REFERENCES LIBROS
);

CREATE TABLE EJEMPLARLIBRO
(SIGNATURA INTEGER NOT NULL,
ISBN INTEGER NOT NULL,
DADADEBAJA VARCHAR (8) NOT NULL,
FECHADADABAJA DATE NULL,
PRIMARY KEY (SIGNATURA),
FOREIGN KEY (ISBN) REFERENCES LIBROS
);

CREATE TABLE PAIS
(COD_PAIS INTEGER NOT NULL,
NOM_PAIS VARCHAR (15) NOT NULL,
PRIMARY KEY (COD_PAIS)
);

CREATE TABLE CIUDAD
(COD_CIUDAD INTEGER NOT NULL,
C_PAIS INTEGER NOT NULL,
NOM_CUIDAD VARCHAR (15) NOT NULL,
PRIMARY KEY (COD_CIUDAD),
FOREIGN KEY (C_PAIS) REFERENCES PAIS
);

CREATE TABLE USUARIO
(CC INTEGER NOT NULL,
NOMBRE VARCHAR(10) NOT NULL,
APELLIDO VARCHAR (15) NOT NULL,
FECHA_NAC DATE CHECK (DATE (NOW()) - DATE (FECHA_NAC) > 6575),
C_CIUDAD INTEGER NOT NULL,
DIRECCION VARCHAR (15) NOT NULL,
NO_CARNET INTEGER UNIQUE, 
CELULAR INTEGER NULL,
FIJO INTEGER NULL,
CORREO VARCHAR(20) NULL,
ESTADO VARCHAR (10) NOT NULL,
MULTA INTEGER DEFAULT 0,
TOTAL_PAGADO INTEGER DEFAULT 0,
PRIMARY KEY (CC),
FOREIGN KEY (C_CIUDAD) REFERENCES CIUDAD
);

CREATE TABLE PROOVEDOR
(NIT INTEGER NOT NULL,
NOMBRE VARCHAR (20) NOT NULL,
TELEFONO INTEGER NOT NULL,
C_CIUDAD INTEGER NOT NULL,
C_PAIS INTEGER NOT NULL,
PRIMARY KEY (NIT),
FOREIGN KEY (C_CIUDAD) REFERENCES CIUDAD,
FOREIGN KEY (C_PAIS) REFERENCES PAIS
);

CREATE TABLE COMPRALIBROS
(CODRECIBO INTEGER NOT NULL,
ISBN INTEGER NOT NULL,
NITPROV INTEGER NOT NULL,
VALORCOMPRA INTEGER NOT NULL,
FECHACOMPRA DATE NOT NULL,
PRIMARY KEY (CODRECIBO),
FOREIGN KEY (ISBN) REFERENCES LIBROS,
FOREIGN KEY (NITPROV) REFERENCES PROOVEDOR
);

CREATE TABLE PRESTAMO
(SIGNATURA INTEGER NOT NULL,
CC_USU INTEGER NOT NULL,
FECHA DATE NOT NULL,
FECHADEVOL DATE NOT NULL,
FECHA_RENOVACION DATE CHECK (DATE (FECHADEVOL) > DATE (FECHA_RENOVACION)),-- AHORA ES LA ULTIMA COLUMNA
NUMRENOVACIONES INTEGER CHECK (NUMRENOVACIONES <3),
FOREIGN KEY (SIGNATURA) REFERENCES EJEMPLARLIBRO,
FOREIGN KEY (CC_USU) REFERENCES USUARIO
);

CREATE TABLE REVISTA
(ISSN INTEGER NOT NULL,
TITULO VARCHAR(15) NOT NULL,
IDIOMA VARCHAR(10) NOT NULL,
ORGANIZACION VARCHAR (10) NOT NULL,
MATERIAS VARCHAR(50) NULL,
PRIMARY KEY (ISSN)
);

CREATE TABLE UBICACIONREV
(ISSN INTEGER NOT NULL,
PISO INTEGER NOT NULL,
ESTANTE INTEGER NOT NULL,
FOREIGN KEY (ISSN) REFERENCES REVISTA
);

CREATE TABLE EJEMPLAREV
(SIGNATURAREV INTEGER NOT NULL,
ISSN INTEGER NOT NULL,
AÑO INTEGER NOT NULL,
MES VARCHAR (10) NOT NULL,
VOLUMEN INTEGER NOT NULL,
FECHAINGRESO DATE NOT NULL,
DADADEBAJA VARCHAR (5) NOT NULL,
FECHADADABAJA DATE NULL,
PRIMARY KEY (SIGNATURAREV),
FOREIGN KEY (ISSN) REFERENCES REVISTA
);

CREATE TABLE SUSCRREV
(ISSN INTEGER NOT NULL,
FECHA DATE NOT NULL,
FECHADESDE DATE CHECK (DATE (FECHA) < DATE(FECHADESDE)),
FECHAHASTA DATE CHECK (DATE (FECHAHASTA) > DATE (FECHADESDE)),
VALOR INTEGER NOT NULL,
FOREIGN KEY (ISSN) REFERENCES REVISTA
);

CREATE TABLE PRESTAMOREV
(SIGNATURAR INTEGER NOT NULL,
CC_USU INTEGER NOT NULL,
FECHA DATE NOT NULL,
FECHADEVOL DATE NOT NULL,
FECHA_RENOVACION DATE CHECK (DATE (FECHADEVOL) > DATE (FECHA_RENOVACION)),
FECHADEVUELTO DATE NULL,
NUMRENOVACIONES INTEGER DEFAULT 0,
FOREIGN KEY (SIGNATURAR) REFERENCES EJEMPLAREV,
FOREIGN KEY (CC_USU) REFERENCES USUARIO
);

CREATE TABLE MULTALIBRO
(CC INTEGER NOT NULL,
SIGNATURALIBRO INTEGER NOT NULL,
FECHADEVOL DATE NOT NULL,
FECHADEVUELTO DATE CHECK (DATE (FECHADEVOL) < FECHADEVUELTO (DATE)),
FOREIGN KEY (CC) REFERENCES USUARIO,
FOREIGN KEY (SIGNATURALIBRO) REFERENCES EJEMPLARLIBRO
);


CREATE TABLE MULTAREVISTA
(CC INTEGER NOT NULL,
SIGNATURAREV INTEGER NOT NULL,
FECHADEVOL DATE NOT NULL,
FECHADEVUELTO DATE CHECK (DATE (FECHADEVOL) < DATE (FECHADEVUELTO)),
FOREIGN KEY (CC) REFERENCES USUARIO,
FOREIGN KEY (SIGNATURAREV) REFERENCES EJEMPLAREV
);

CREATE TABLE BDDIGITAL
(NOMBRE VARCHAR(15) NOT NULL,
PROOVEDOR INTEGER NOT NULL,
AREADDECONOCIMIENTO VARCHAR(50) NOT NULL,
PRIMARY KEY (NOMBRE),
FOREIGN KEY (PROOVEDOR) REFERENCES PROOVEDOR
);

CREATE TABLE SUSCRBDDIGITAL
(NOMBRE VARCHAR(15) NOT NULL,
FECHA DATE NOT NULL,
VIGENCIADESDE DATE CHECK (DATE (FECHA) < DATE (VIGENCIADESDE)),
VIGENCIAHASTA DATE CHECK (DATE (VIGENCIADESDE) < DATE (VIGENCIAHASTA)),
CLAVE VARCHAR (15) NOT NULL,
FOREIGN KEY (NOMBRE) REFERENCES BDDIGITAL
);

CREATE TABLE RENOVABDDIGITAL
(NOMBRE VARCHAR(15) NOT NULL,
FECHA DATE NOT NULL,--FECHA EN QUE SE HACE LA RENOVACION
VIGENCIADESDE DATE CHECK (DATE (FECHA) < DATE (VIGENCIADESDE)),
VIGENCIAHASTA DATE CHECK (DATE (VIGENCIADESDE) < DATE (VIGENCIAHASTA)),
FOREIGN KEY (NOMBRE) REFERENCES BDDIGITAL
);

----------------------------CONSTRAINTS EXTRAS------------------------------

ALTER TABLE PRESTAMO DROP COLUMN FECHA_RENOVACION;
ALTER TABLE PRESTAMO ADD COLUMN RENOVACION DATE NULL 
CHECK (DATE (FECHADEVOL) > DATE (RENOVACION));

ALTER TABLE PRESTAMO ADD FOREIGN KEY (SIGNATURA) REFERENCES EJEMPLARLIBRO; -- UN DETALLE QUE SE NOS PASO DE LARGO

ALTER TABLE LIBROS ADD COLUMN CANTPRESTAMOS INTEGER DEFAULT 0;

ALTER TABLE SUSCRREV ADD COLUMN CC_USU INTEGER NOT NULL;
ALTER TABLE SUSCRREV ADD FOREIGN KEY (CC_USU) REFERENCES USUARIO;

ALTER TABLE MULTALIBRO ADD COLUMN VALOR INTEGER NOT NULL; 

ALTER TABLE SUSCRBDDIGITAL ADD COLUMN CC_USU INTEGER NOT NULL;
ALTER TABLE SUSCRBDDIGITAL ADD FOREIGN KEY (CC_USU) REFERENCES USUARIO;

ALTER TABLE RENOVABDDIGITAL ADD COLUMN CC_USU INTEGER NOT NULL;
ALTER TABLE RENOVABDDIGITAL ADD FOREIGN KEY (CC_USU) REFERENCES USUARIO;

ALTER TABLE REVISTA ADD COLUMN NUMEJEMPLARES INTEGER DEFAULT 3;